# Generated by Django 4.2.6 on 2024-07-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HadithBooksArabic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=255)),
                ('book_number', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hadith Book Arabic',
                'verbose_name_plural': 'Hadith Books Arabic',
            },
        ),
        migrations.CreateModel(
            name='HadithBooksEnglish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=255)),
                ('book_number', models.PositiveSmallIntegerField()),
                ('source', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hadith Book English',
                'verbose_name_plural': 'Hadith Books English',
            },
        ),
        migrations.CreateModel(
            name='IcHadithEnglish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hadith_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hadith_text', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='reciation.hadithbooksenglish')),
            ],
            options={
                'verbose_name': 'Hadith English',
                'verbose_name_plural': 'Hadith English',
                'db_table': 'ic_hadith_english',
            },
        ),
        migrations.CreateModel(
            name='IcHadithArabic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hadith_number', models.CharField(blank=True, max_length=15, null=True)),
                ('hadith_text', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiths', to='reciation.hadithbooksarabic')),
            ],
            options={
                'verbose_name': 'Hadith Arabic',
                'verbose_name_plural': 'Hadith Arabic',
                'db_table': 'ic_hadith_arabic',
            },
        ),
    ]
