# Generated by Django 4.2.6 on 2024-01-31 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.FileField(blank=True, null=True, upload_to='forum_upload/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_users', models.ManyToManyField(related_name='interested_forums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
