# Generated by Django 4.2.6 on 2023-10-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog_post_images/'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog_post_images/'),
        ),
    ]
